### ISSUE TITLE
Sprockets AssetNotPrecompiledError in Rails 7

### ISSUE THREAD

**Issue by onurozer** [Dreamersoul/administrate-field-active_storage#103]
Hi, 

I am using Rails 7 with esbuild and tailwind css. I tried adding `attachment: Field::ActiveStorage,` to an Active Storage field in administrate and got this error: 

**Sprockets::Rails::Helper::AssetNotPrecompiledError**
```
Asset `administrate-field-active_storage/application.css` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link administrate-field-active_storage/application.css
```

Administrate [doesn't seem to support Rails 7 yet](https://github.com/thoughtbot/administrate/issues/2091#issuecomment-1012358920), so [I'm using a fork](https://github.com/thoughtbot/administrate/issues/2091#issuecomment-1017343152). 

The error I'm getting seems to be similar to the problem with the original administrate branch regarding asset compilation, but I may be wrong. 

Is there a way to get this plugin to work with Rails 7 defaults and administrate? 

Thank you.

**Comment by Dreamersoul** [comment]
I haven't looked into it yet if you find a fix please feel free to submit a PR

**Comment by edudepetris** [comment]
@onurozer have you tried to add `//= link administrate-field-active_storage/application.css` into your manifest? ([example](https://github.com/Dreamersoul/administrate-field-active_storage/commit/9065e05bf81b05d827e64169a4632bb9a9792798))

**Comment by Dreamersoul** [comment]
no response from issue creator. closing for now.
please open a new issue if you still having issues 👍🏻

**Comment by clayton** [comment]
This is still happening with rails 7.0.7

The error:
```
Asset `administrate-field-active_storage/application.css` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link administrate-field-active_storage/application.css
```

Modifying `app/assets/config/manifest.js` to include the snippet above:

```
//= link administrate-field-active_storage/application.css
//= link_tree ../images
//= link_directory ../stylesheets .css
//= link_tree ../../javascript .js
//= link_tree ../../../vendor/javascript .js
//= link_tree ../builds
```

I ran `rails assets:clobber` for good measure and restarted the server.

Seems to have fix the issue, but noticed some errors with my rspec feature specs. Not sure if related.
