### ISSUE TITLE
Images not showing in production.

### ISSUE THREAD

**Issue by czepesch** [Dreamersoul/administrate-field-active_storage#107]
Hi.
I was trying to deploy Rails 7 Tailwind app using Dokku, but build was getting error:
`SassC::SyntaxError: Error: Function rgb is missing argument $green.
       on line 1 of stdin
       >> en-700{--tw-border-opacity:1;border-color:rgb(21 128 61/var`
So I had to use fork of Administrate gem which fixes this issue:
https://github.com/thoughtbot/administrate/pull/2116

Now app is deploying like it should, but images in /admin section are not displayed 
![image](https://user-images.githubusercontent.com/54212560/178311941-7ef06bdd-2528-4d95-90e5-71c33dfbf79b.png)

This exactly image is displayed on frontend though:
![image](https://user-images.githubusercontent.com/54212560/178313746-814873cc-b299-4b33-b64b-9b1ad1ce22ca.png)

be so kind to give me a hint, maybe I forgot something or misunderstood.
Thanks.

**Comment by Dreamersoul** [comment]
sorry for taking too long to respond, honestly it works fine with me maybe your configuration is incorrect? 
honestly looks like a sass issue. what does the network call tell you?

**Comment by czepesch** [comment]
> sorry for taking too long to respond

Hi! it's okay. 
As far I understand I can't use sass at all, because I use Tailwind and I need Stimulus.
Is sassc is present I can't deploy: `SassC::SyntaxError: Error: Function rgb is missing argument $green`
If I use fork of Administrate where SassC is removed - Stimulus not working, because of the bug with `date-picker`.
There is a fork where date-picker bug is fixed, but it still depends on SassC, so I can't deploy again 😄 vicious circle.

**Comment by Dreamersoul** [comment]
@czepesch haha reminds me when we first adopted flutter v2 and dart turned null safety on. Took months for all the libraries to get updated.

From the looks of it the issue isn't from our gem as it simply shows the image without any sass, just a simple css file that makes it look tidy

I think the issue is with adminstrate itself

If you can post a sample project I might be able to help more 🙏🏻

**Comment by czepesch** [comment]
@Dreamersoul yes, repo is public, you can look at it: https://github.com/r-rails/plants
For now removed both administrate and field-active_storage. Not sure if you can help me and and I can live with that problem for a while, not super urgent. It would be just nice to have dashboard.

**Comment by SanzPlusNB** [comment]
same error here, preview not showing, but clicking the file name downloads the file, and works fine on the view itself. rails 7 + tailwind.

**Comment by cyu** [comment]
I was able to fix this issue by installing libvips.  The field is trying to show a variant and since libvips doesn't exist, it can't generate that variant, hence that broken image.
