### ISSUE TITLE
undefined method `attached?' for #<ActiveRecord::Associations::CollectionProxy []>

### ISSUE THREAD

**Issue by richjdsmith** [Dreamersoul/administrate-field-active_storage#11]
Gem is failing on line 17 of
`administrate-field-active_storage (0.1.3) app/views/fields/active_storage/_show.html.erb`

Not sure where to begin.

**Comment by Dreamersoul** [comment]
can i please have an example of the models file? and the dashboard file from administrate?

**Comment by richjdsmith** [comment]
I can certainly share those files, but am also happy to give you access to the private repo if it'd be easier? It is on gitlab.

lemme know whats easier and I'll do that.

**Comment by richjdsmith** [comment]
Nevermind, I just pushed a copy up to github

here's the repo

https://github.com/richjdsmith/nobull_app

Go back one version to see it failing on the plugin (current branch has a patchwork fix)

**Comment by richjdsmith** [comment]
I'll dig into this and see if I can't figure out where I went wrong next week. If I find something, I'll follow up. For now I will close though, because I think you're right  that its not related to your gem.

Thanks for being a big part of the open source community! 🥇

**Comment by fikrikarim** [comment]
@richjdsmith Heyy did you find any solution? I encountered the exact problem.. I would be so grateful if you can share some findings thanks. 👍

**Comment by richjdsmith** [comment]
@fikrikarim  Unfortunately I never did. I still plan on looking into it, but just haven't had a chance to yet.
