### ISSUE TITLE
field-active_storage nested  => Administrate::Field::ActiveStorage#attached?** delegated to data.attached?

### ISSUE THREAD

**Issue by v2lrf** [Dreamersoul/administrate-field-active_storage#13]
### The awesome administrate-field-active_storage is combined with the administrate-field-nested_has_many GEM

![capture d ecran 2019-01-31 a 20 01 22](https://user-images.githubusercontent.com/24680535/52078436-7b443a80-2593-11e9-8814-6716c23f455e.jpg)

Not sure where to begin. 

I'm investigating the issue  - or the challenge which is in front of me right now. I think to be honest, my brain is burned tonight. But maybe it's not an issue from the Gem (the gem works) and it's just a features to plan... in case of i missed something in my code.

```the use case```

I actually need to work withing a Nested form relation between Users and Projects ```has_one_attached :header_image_project```

Why i need it ? Cause i and probably some other devs will probably need it. I will add almost 15 pictures by project and a title a description... for all pictures. That’s why nested form has many  is 😇 . Right there the challenge is just to nest project (which include one single picture) to a user form. Once done the schema will be different and a table like projects_pictures for instance will belongs to projects table. 

```the final job could be like this, for instance.```
![image 2](https://user-images.githubusercontent.com/24680535/52111006-b6ca1d80-2602-11e9-8d41-e46c16db1eeb.jpg)

 But let’s start simple :-) and see what look like the current schema and table
```below Here the visual schema ```

![capture d ecran 2019-01-31 a 21 32 24 copie](https://user-images.githubusercontent.com/24680535/52084213-d2510c00-25a1-11e9-988d-b44b8d5f69a5.jpg)

```#user.rb```
```ruby
has_many :projects
accepts_nested_attributes_for :projects, reject_if: :all_blank, allow_destroy: true
```

```#project.rb```
```ruby
has_one_attached :header_image_project
belongs_to :user
```

```#user_dashboard.rb```
```ruby
class UserDashboard < Administrate::BaseDashboard
ATTRIBUTE_TYPES = {
    ...
    password: Field::Password,
    projects: Field::NestedHasMany.with_options(skip: :user, limit: 5), 
    # 👆🏼field from the Gem nested_has_many
    ...
 ` }.freeze`

   ...
FORM_ATTRIBUTES = [
    ...
    :password,
    :projects,
    ...
  ].freeze

end
```

```#projet_dashboard.rb```
```ruby
class ProjectDashboard < Administrate::BaseDashboard

  ATTRIBUTE_TYPES = {
    ...
    user: Field::BelongsTo,
    project_name: Field::String,
    header_image_project: Field::ActiveStorage,
    ...
  }.freeze

   ...

  FORM_ATTRIBUTES = [
    :user,
    :header_image_project,
    :project_name,
  ].freeze

end
```

```#schema.rb```
```ruby
create_table "projects", force: :cascade do |t|
    t.string "project_name"
    t.bigint "user_id"
    t.index ["user_id"], name: "index_projects_on_user_id"
  end

create_table "users", force: :cascade do |t|
    ...
    t.index ["email"], name: "index_users_on_email", unique: true
  end
```

So at the end it seems to be not possible yet to build nested form which include "one or more attached file " from active storage. 

If I missed something in my code I will probably get the mistake by myself, and that post will help others I think . 

If my code is  fine, so a PR could be the next step. I never did one before for a Gem, I would be very happy to help. Do you have any line of thought ? What is the best practice according you ? And where does the problem come and from which Gem ?

**Comment by Dreamersoul** [comment]
the code looks fine! im guessing the delegate attribute should check for nil
for example
```ruby
    delegate :attached?, to: :data if !data.nil?
    delegate :attachments, to: :data if !data.nil?
```

to be honest i have never worked with `administrate-field-nested_has_many` so im guessing it initializes the model with nil to show empty fields?

you could test if the code i wrote above works with your requirement and submit a PR! to test you could use the example project while editing the gem! let me know if you need help

i will try to fix it soon if i have the time! thank you for reporting 👍

**Comment by laviedesanges** [comment]
> ```ruby
>     delegate :attached?, to: :data if !data.nil?
>     delegate :attachments, to: :data if !data.nil?
> ```
> you could test if the code i wrote above works with your requirement and submit a PR! to test you could use the example project while editing the gem! let me know if you need help

So glad to read your comment @Dreamersoul. Thank you for your answer. I just tested tonight and I have this message error below. I will probably investigate further once job done.

```/Users/hhgb12/code/HHGB12/16_gems/administrate-field-active_storage/lib/administrate/field/active_storage.rb:52:in `<class:ActiveStorage>': undefined local variable or method `data' for Administrate::Field::ActiveStorage:Class (NameError)```

**Comment by HHGB12** [comment]
> ```ruby
>     delegate :attached?, to: :data if !data.nil?
>     delegate :attachments, to: :data if !data.nil?
> ```
> you could test if the code i wrote above works with your requirement and submit a PR! to test you could use the example project while editing the gem! let me know if you need help
> 
> i will try to fix it soon if i have the time! thank you for reporting 👍

So glad to read your comment @Dreamersoul. Thank you for your answer. I just got a break at work. I just test your proposition code. II can't launch the local server. I have the message below.

```.../Users/hhgb12/code/HHGB12/16_gems/administrate-field-active_storage/lib/administrate/field/active_storage.rb:52:in `<class:ActiveStorage>': undefined local variable or method `data' for Administrate::Field::ActiveStorage:Class (NameError)```

I will investigate further the gem I'll let you know,

**Comment by Dreamersoul** [comment]
Thanks I will be waiting!

**Comment by HHGB12** [comment]
Hi, @Dreamersoul  I'm still on it 😱 and can't figure out yet the right way to win.
However, it seems that whether for create or edit I have a similar error message which is not usual. 


``` ruby
Module::DelegationError - Administrate::Field::ActiveStorage#attached? delegated 
to data.attached?, but data is nil: 
#<Administrate::Field::ActiveStorage:0x00007fee2837a2a8 
@attribute=:project_picture, @data=nil, @page=:form, @resource=#
<ActiveRecord::Associations::CollectionProxy []>, @options={}>:
```

```ruby
Module::DelegationError - Administrate::Field::ActiveStorage#attached? 
delegated to data.attached?, but data is nil: #<Administrate::Field::ActiveStorage:0x00007fee2a049cd0 @attribute=:project_picture, 
@data=nil, @page=:form, @resource=#<ActiveRecord::Associations::CollectionProxy 
[#<ProjectPicture id: 1, description: "on first description", project_id: 1, 
created_at: "2019-02-13 20:46:30", updated_at: "2019-02-13 20:46:30">]>, @options={}>:
```

Just to explain the final goal in case of others could be interested in. 
Build a form which nest the has_many project_pictures model (description and picture).
The current challenge is here cause i also use the nested_has_many Gem. 
 
`#project.rb`

```ruby
has_many :project_pictures
accepts_nested_attributes_for :project_pictures, reject_if: :all_blank, allow_destroy: true
```

`#project_picture.rb`

```ruby
belongs_to :project
```


The deal is to temporary find a solution to move forward. So i'm little shamed, and not really proud of it but let say that instead of create projects picture one by one... cause nested has_many option failed (today) . With a callback i build a bunch of it after having created the Project itself. Then i will just have to update each row with the correct description and the correct picture. And i only display Project_picture with name !=  "I'm a virgin description"

inside ```#project.rb```
```ruby
# == Callbacks =======================
   after_create :set_10_virgins_project_pictures
# == Instance Methods ================
  def set_10_virgins_project_pictures
    10.times do
      ProjectPicture.create!(description: "i'm a virgin description", project: self)
    end
   # The objetif is to get a bunch of already project_pictures buit. 
   # Then only have to edit it and rename it to publish it.
  end
```

Hopefully i will figure out out to manage field_nested_has_may Gem a administrate-field-active_storage GEM but let's say that it work like this.

![capture d ecran 2019-02-13 a 23 20 51](https://user-images.githubusercontent.com/24680535/52748274-64b3cf80-2fe6-11e9-9c74-8ea2e36e701e.jpg)

I would be very happy to propose a PR for that challenge but at this time the only thing that i can provide is this post. But still on it. 🙌

**Comment by Dreamersoul** [comment]
Awesome work! Getting those small solutions to work will bring us closer to the issue! I'm guessing we need to know what the field_nested_has_many gem sends throughout the controller and try to find a solution maybe an initializer or some changes either from their end or our end! If you can, can you prepare an example project and link it here so I can get a head start?

**Comment by HHGB12** [comment]
> [...] If you can, can you prepare an example project and link it here so I can get a head start?

👍🏼 ok i'll add the link asap

**Comment by Dreamersoul** [comment]
Hello, any updates?

**Comment by HHGB12** [comment]
> Hello, any updates?

Hi @Dreamersoul
A month, already a month since my last post. I need One extra week to deliver a project.
Once this job done, I will take time on the issue.
> If you can, can you prepare an example project and link it here so I can get a head start?

As you propose i ll push a branch, and then we will start working on.
 I'm really sorry for that delay.

**Comment by imgarylai** [comment]
> the code looks fine! im guessing the delegate attribute should check for nil
> for example
> 
> ```ruby
>     delegate :attached?, to: :data if !data.nil?
>     delegate :attachments, to: :data if !data.nil?
> ```
> 
> to be honest i have never worked with `administrate-field-nested_has_many` so im guessing it initializes the model with nil to show empty fields?
> 
> you could test if the code i wrote above works with your requirement and submit a PR! to test you could use the example project while editing the gem! let me know if you need help
> 
> i will try to fix it soon if i have the time! thank you for reporting 👍

Is this on the roadmap?

**Comment by Dreamersoul** [comment]
@imgarylai I honestly don't think so since I don't use `administrate-field-nested_has_many`. However if someone is willing to implement it and submit a PR id be happy to review the code, test it and merge

**Comment by evgeniy-khlopin** [comment]
Hello. I've faced exactly the same issue.
My solution was to override the field-active_storage [_form.html.erb](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_form.html.erb).
Changing `<% if field.attached? %>` to `<% if field.present? %>` make things work.
I'm not sure if this a good solution, but it works for me anyway.

**Comment by v2lrf** [comment]
> Hello. I've faced exactly the same issue.
> My solution was to override the field-active_storage [_form.html.erb](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_form.html.erb).
> Changing `<% if field.attached? %>` to `<% if field.present? %>` make things work.
> I'm not sure if this a good solution, but it works for me anyway.
@evgeniy-khlopin  
this is very good news I 'll check it. let's say that things are moving thanks for that 'temporary' trick

**Comment by Dreamersoul** [comment]
Thank you for the feedback Please submit a PR and add yourself as a contributor in the markdown file
