### ISSUE TITLE
Attaching images work with one model and donn't work with anoter

### ISSUE THREAD

**Issue by Mracobes9** [Dreamersoul/administrate-field-active_storage#15]
Hi. I have a problem with you gem. I have to model: Drink and Food. They can to have many images. But Food works fine, and Drink raised error? when i try to open Edit page: ```
 Showing /home/mracobes/.rvm/gems/ruby-2.5.1/gems/administrate-0.11.0/app/views/fields/has_many/_form.html.erb where line #27 raised:

uninitialized constant ActiveStorage::AttachmentDashboard
```

**Comment by Dreamersoul** [comment]
Can I please have an example of the code? The dashboard and the model files
please

**Comment by Dreamersoul** [comment]
this is being closed for being inactive. if you still have an issue please submit a new issue with more information
