### ISSUE TITLE
N+1 Issue in Index and Show Page

### ISSUE THREAD

**Issue by deltapurna** [Dreamersoul/administrate-field-active_storage#17]
Salam Hamad,

Thanks a lot for your work with this gem. It really helps my work.

I've observed that when the attribute is activated in collection (index) page, the resources will do multiple queries to fetch the image attachments. This is also happens when we have a have many attachment relation in show page.

Is it possible to use the active storage scope `with_attached_*` in the query?

Let me know if this has been resolved or I simply use the gem wrongly.

Thanks!

**Comment by Dreamersoul** [comment]
Salam!
I forgot to accommodate the gem with that following scope! I'll research it however I think the developer using the gem should do the change in their ModelDashboard file.
If you find a way to add a scope to the dashboard feel free to update the readme file and submit a PR

If not I'll look into it soon, thank you!

**Comment by deltapurna** [comment]
got it, will try to look into that Hamad. Ideally it should be possible to append the scope by default without overriding the ModelDashboard.

Note: I never build any gem before haha. But let me see what I can do.

**Comment by Dreamersoul** [comment]
Yeah ideally it should but I think the way administate is built we can do that from a field gem.

Don't worry haha if you need any help I'm here.

**Comment by deltapurna** [comment]
I did a little dig in to resolve this issue. But I don't think there's a way to automatically append a scope when the developer setup the custom field.

So I think the best way to resolve this for now is to add in the docs (the `README` file) on recommendation to add the `with_attached_*` scope in their own resource controller to prevent N+1 problem. Administrate actually has generated an empty controller when the developer add a new resource dashboard (https://administrate-prototype.herokuapp.com/customizing_controller_actions).

What do you think?

**Comment by deltapurna** [comment]
Woah. that's fast haha. Awesome!

**Comment by Dreamersoul** [comment]
Haha I love working on this gem tbh
