### ISSUE TITLE
Any reason why the "image_processing" gem is required?

### ISSUE THREAD

**Issue by rnaud** [Dreamersoul/administrate-field-active_storage#172]
I would assume we could just show the full file as a preview. 
I'm not sure that I understand why the image_processing gem would be required. 

Any pointer on how I can make this optional?

**Comment by rnaud** [comment]
My bad, the gem is totally optional.

I was able to skip it by using this as mentioned in the documentation.

```
# this skips the variant auto generation
image: Field::ActiveStorage.with_options(show_preview_variant: false)
```

Should we update the README to make it clear that the gem is optional?

**Comment by Dreamersoul** [comment]
Yes adding it to the readme would be helpful if you can submit a PR I'd appreciate it
