### ISSUE TITLE
Rails 6 `Field::ActiveStorage.with_options(show_preview_size: ...)` does not return preview images (as expected)

### ISSUE THREAD

**Issue by bunnymatic** [Dreamersoul/administrate-field-active_storage#27]
On Rails 6, 
if i specify a `show_preview_size` in the options, I see the following deprecation warning followed by an error from `image_processing` gem when we try to build a variant.

```DEPRECATION WARNING: Active Storage's ImageProcessing transformer doesn't support :combine_options, as it always generates a single ImageMagick command. Passing :combine_options will not be supported in Rails 6.1. (called from each at /Users/jon/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activestorage-6.0.2.1/lib/active_storage/transformers/image_processing_transformer.rb:23)```

```ArgumentError - wrong number of arguments (given 1, expected 2):```

```
# in my dashboard definition
ATTRIBUTE_TYPES = {
    ...
    image: Field::ActiveStorage.with_options(show_preview_size: "150x200>"),
    ...
}
```

It looks like the way options are being handled needs to be changed if `show_preview_size:` is going to work with Rails6 active storage.

If I leave out the options (`image: Field::ActiveStorage`), things work as expected.

From my Gemfile.lock
```
administrate (0.12.0)
administrate-field-active_storage (0.2.1)
image_processing (1.10.3)
rails (6.0.2.1)
```

I'm going to take a few minutes to see if I can get a PR together to solve this but if you have any thoughts around this issue, let me know.

**Comment by Dreamersoul** [comment]
Thank you for the information! I think the api should change, I'll try to fix it and submit a PR tomorrow

**Comment by bunnymatic** [comment]
Interestingly, I noticed in your code, you default to 
``` # lib/administrate/field/active_storage.rb
def show_preview_size
    options.fetch(:show_preview_size, [1080, 1920])
end
```
And my setting was with a string (which I think I found in docs somewhere).  Is that the issue?  Am I mis-using the option?

**Comment by Dreamersoul** [comment]
I think I forgot to update the docs! What happens when you send an array of numbers instead of a string?

**Comment by bunnymatic** [comment]
Well, that's an easy fix.  
```     image: Field::ActiveStorage.with_options(show_preview_size: [100, 200]),
``` works just fine.

If you are going to update the docs, can you explain how this crop works?  is it `fit` or `cover`?  

thanks

**Comment by Dreamersoul** [comment]
The crop uses cover not fit if I recall correctly! I'll leave this issue open so I don't forget to update the docs, you are welcome to update the docs through a PR, add your name to the contributers markdown if you do so!
