### ISSUE TITLE
Link to and download original (full size) image?

### ISSUE THREAD

**Issue by sedubois** [Dreamersoul/administrate-field-active_storage#29]
Hello, thank you for this gem!

I am able to use this gem to preview images in the dashboard, as follows:
```rb
cover_image: Field::ActiveStorage.with_options(
  show_in_index: true,
  direct_upload: true,
  show_preview_size:  [400, 400]
)
```

<img width="596" alt="Screenshot 2020-02-26 at 08 43 55" src="https://user-images.githubusercontent.com/4217871/75322957-277a5280-5874-11ea-8f10-f631d817dc87.png">

This makes a small image which is great, but I would like to be able to see the image in its original size as well somehow, with an easy way to download it (if possible without needing to right-click > download image as...). For instance clicking the image would open a new tab or a modal showing the original full size image and/or a button to download. The same would ideally apply to other types of attachments such as videos or audios. Is there a way to achieve that?

Two other questions (not super important):
- it would be nice if the "1 attached file" in the index was hidden when there is only 1 attached file (or that this could be configurable), especially when it's for a `has_one_attached` like below;
- it would be nice to be able to show a different preview size on the index and show pages (typically, a very small preview on the index and a bigger one on the show page).

<img width="396" alt="Screenshot 2020-02-26 at 08 45 21" src="https://user-images.githubusercontent.com/4217871/75323019-57295a80-5874-11ea-8310-25576ea1621f.png">

**Comment by Dreamersoul** [comment]
It should be easy but I'm currently a bit busy if you check the code it's not that complicated, I'm open for PR :)

**Comment by sedubois** [comment]
OK I've managed by overriding views as follows:

Override `_item.html.erb` to allow downlading source attachment by clicking on it, showing filename in the tooltip text,  and only showing the number of attachments if greater than 1 or `-` if 0:
```rb
<%
  # By default we don't allow attachment removal
  removable = local_assigns.fetch(:removable, false)
  image_size = local_assigns.fetch(:image_size, [1920, 1080])
%>

<%= link_to(field.blob_url(attachment), title: attachment.filename) do %>
  <% if attachment.image? and !field.url_only? %>
    <%= image_tag(field.variant(attachment, resize_to_limit: image_size)) %>
  <% elsif attachment.video? and attachment.previewable? and !field.url_only? %> <%# if ffmpeg is installed %>
    <%= video_tag(field.url(attachment), poster: field.preview(attachment, resize_to_limit: image_size), controls: true, autobuffer: true, style: "width: 100%; height: auto;") %>
  <% elsif attachment.video? and !field.url_only? %>
    <%= video_tag(field.url(attachment), controls: true, autobuffer: true, style: "width: 100%; height: auto;") %>
  <% elsif attachment.audio? and !field.url_only? %>
    <%= audio_tag(field.url(attachment), autoplay: false, controls: true) %>
  <% elsif attachment.previewable? and !field.url_only? %>
    <%= image_tag(field.preview(attachment, resize_to_limit: [595, 842])) %>
  <% else %>
    <%= attachment.filename %>
  <% end %>
<% end %>

<% if removable %>
  <%= link_to 'Remove', field.destroy_path(field, attachment), method: :delete, class: 'remove-attachment-link' %>
  <hr>
<% end %>
```

Override `_index.html.erb` to have image size of 150x150 on index page:
```rb
<style> <%# figure out a way to remove this %>
  td img {
      max-height: unset !important;
  }
</style>
<% 
  attachments = Array(field.many? ? field.attachments : field.data)
%>
<% if field.attached? %>
  <% if field.show_in_index? %>
    <%= render partial: 'fields/active_storage/item', locals: { field: field, attachment: attachments[0], image_size: [150, 150] } %>
  <% end %>
  <%= pluralize(attachments.count, 'Attached file') if attachments.count > 1 %>
<% else %>
-
<% end %>
```

**Comment by Dreamersoul** [comment]
Wouldn't it be better to have it as link under the image (download full size) and make it an option the developer enables?

**Comment by sedubois** [comment]
In the case of an image (my use case) I think it makes more sense for it to be clickable, but it's true this might not work well for other types of attachments.

**Comment by sedubois** [comment]
Also, a text like "Download full size" would be bothersome on an index view where space is tight.
