### ISSUE TITLE
Media library: allow to pick from existing attachments

### ISSUE THREAD

**Issue by sedubois** [Dreamersoul/administrate-field-active_storage#30]
Would there be any way to be able to pick an attachment from existing ActiveStorage blobs instead of having to re-upload every time? Similar to the way it is done in Wordpress or other CMSes. Might be just a dream but I thought I'd ask in case there is a solution out there!

**Comment by Dreamersoul** [comment]
to be honest this feels like a general active storage question haha, i honestly done know but I'll keep this open if someone can implement it. thanks for taking interest in the project

**Comment by sedubois** [comment]
Yes, I've also opened https://github.com/thoughtbot/administrate/issues/1560. Feel free to close or keep open as you prefer...

**Comment by sedubois** [comment]
Actually isn't this rather a question about how to configure a polymorphic field? That is the way the ActiveStorage::Attachments table works ([doc](https://edgeguides.rubyonrails.org/active_storage_overview.html)):

> active_storage_attachments is a polymorphic join table that stores your model's class name. If your model's class name changes, you will need to run a migration on this table to update the underlying record_type to your model's new class name.

And Administrate does have a `Field::Polymorphic` with a `:classes` option which allows to "Specify a list of classes whose objects will be used to populate select boxes for editing this polymorphic field" ([doc](http://administrate-prototype.herokuapp.com/customizing_dashboards)).

So `administrate-field-active_storage` could have two parts, one to upload an attachment (as it already does) and another to pick from existing attachments using `Field::Polymorphic`.

**Comment by Dreamersoul** [comment]
sounds interesting to be honest and i would love to have it in the gem ( would probably bump the gem to v2.0.0 with that) however due to time constrains I'm unable to add new features such as the following, you can create a branch (calling at media library works) with a PR and ill help around with it.

**Comment by sedubois** [comment]
I'm in the same situation. Let's see if/when someone has a chance to try something.

**Comment by sedubois** [comment]
I made progress, documented here:
https://github.com/thoughtbot/administrate/issues/1560#issuecomment-606057998

As far as this gem is concerned and at this point, I think the next step would be to find a way to render the blobs' previews in the context of the blob table. E.g. when viewing `/admin/active_storage/blobs/:id` we should be able to see what the blob looks like (i.e. to render an image if it's an image, etc). 

@Dreamersoul any idea how to proceed?

**Comment by Dreamersoul** [comment]
I remember that you can render the blobs by using preview links something like this 
[Link](https://api.rubyonrails.org/classes/ActiveStorage/Blob/Representable.html#method-i-preview)

**Comment by sedubois** [comment]
Yes, it would be great if `Administrate::Field::ActiveStorage` was able to handle something like that:
```rb

class ActiveStorage::BlobDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    ...
    preview: Administrate::Field::ActiveStorage
  }.freeze

  SHOW_PAGE_ATTRIBUTES = %i[
  ...
  preview
  ]
```

This doesn't work currently, throws error.

**Comment by sedubois** [comment]
We actually want to use `variant`, not preview. Basically there should be a way to render the same view as this gem already provides, but in the context of a blob rather than as an attachment.

**Comment by Dreamersoul** [comment]
I think it would be better if it had another field to it maybe `Administrate​::​Field​::​ActiveStoragePreview` for such an operation?

**Comment by sedubois** [comment]
Come to think of it, depending on the file type it would need to display a preview, a variant or just the bob's URL + a hyperlink to download the blob, so I don't know if "preview" is the most descriptive. How about "embed"? When you think about it what we want is to show the "real thing" as much as possible, instead of just showing a preview image. For instance for videos, the gem displays an actual embedded video player and not the preview image of the video. It's just that this logic still needs to be continued for other file types such as PDFs or other documents (AFAIK, these are still only shown as images). Anyway I'm just trying to point out that this field's focus, and thus naming, should probably rather be on embeds rather than previews?

On the other hand, how would this field be fundamentally different from `Administrate::Field::ActiveStorage`? This new field would be about displaying the embed and providing a download link, whereas the other one is additionally concerned with actually uploading/attaching blobs to another resource as well as purging them. So maybe the existing field could be renamed to `Adminstrate::Field::ActiveStorageAttachment` and this new one could be named `Administrate::Field::ActiveStorageEmbed` (Just my current ideas...). The `ActiveStorageAttachment` field would extend the functionality of `ActiveStorageEmbed` as it also needs to render the embed.

There is also the question raised earlier of how to display this field within the `ActiveStorage::Blob` dashboard. Maybe a field name like `embed` would do even though it doesn't correspond to any `embed` attribute on the resource. The data needed to render the embed would be available from the blob resource itself anyway:
```rb
  ATTRIBUTE_TYPES = {
    ...
    embed: Administrate::Field::ActiveStorageEmbed
  }.freeze
```

**Comment by sedubois** [comment]
It would also be nice if whatever name we choose for the field did not appear in the left-side column like with other fields but instead could just be hidden. That way we don't really need to worry how it's called. 

<img width="700" alt="Screenshot 2020-03-31 at 09 33 17" src="https://user-images.githubusercontent.com/4217871/78012226-f692af00-7344-11ea-8b2f-42a9dc079e41.png">
Like this:

**Comment by Dreamersoul** [comment]
No think the way to go in terms of adding a media library is create a custom view that show cases blobs and allows to download them, then allow the attaching of said file to a record, we can decide on the naming later on 👍🏼

**Comment by sedubois** [comment]
For more thinking about this, see https://github.com/thoughtbot/administrate/issues/1611.
