### ISSUE TITLE
Is mini_magick an implicit requirement of this gem?

### ISSUE THREAD

**Issue by padi** [Dreamersoul/administrate-field-active_storage#33]
Installed for Rails 5.2
`gem 'administrate-field-active_storage' -v 0.1.8`

... and just followed the instructions for `has_one_attached` and the show page of the admin dashboard just gives me:

```
LoadError (cannot load such file -- mini_magick):
```

Just installing `mini_magick` gem works for me but I figure this could easily trip other people up.

I'll include it myself in the `Things to Know` section if that's the best course of action.

**Comment by Dreamersoul** [comment]
Oh yeah that's correct, forgot to add it, I would appreciate that!
