### ISSUE TITLE
show_display_preview doesn't seem to have an effect

### ISSUE THREAD

**Issue by leifg** [Dreamersoul/administrate-field-active_storage#37]
If I understand correctly: With the implementation of #35 for attachment display tweaks, the option to hide the preview image completely changed from `url_only: true` to `show_display_preview: false`.

Making that change does not seem to have an effect however.

In addition I did a quick code search and found that the helper method [show_display_preview?](https://github.com/Dreamersoul/administrate-field-active_storage/blob/99ed567bb5785cc548d65cb01cbb1e07820c753e/lib/administrate/field/active_storage.rb#L22) is never read.

How do I turn off the preview all together in the latest version?

**Comment by Dreamersoul** [comment]
Oh apologies, I must've missed that at the review, will take a look at it and push a bug fix

**Comment by Dreamersoul** [comment]
this is fixed now however ive been meaning to add testing to this gem, can you help with issue #2 ? 
@sedubois @leifg 
thank you both for the amazing contributions to this gem

**Comment by sedubois** [comment]
Sorry about that bug, yes tests would be needed. I'll let you know if I have a chance to work on that.

**Comment by sedubois** [comment]
@Dreamersoul FYI you seem to have made a release on Rubygems (version 0.3.2) but it is not visible on GitHub.

**Comment by Dreamersoul** [comment]
uploading it now thanks!
