### ISSUE TITLE
undefined method  ...path when using has_one_attached

### ISSUE THREAD

**Issue by wilpar** [Dreamersoul/administrate-field-active_storage#38]
```
ATTRIBUTE_TYPES = {
primary_image: Field::ActiveStorage,
...
...
}.freeze

SHOW_PAGE_ATTRIBUTES = %i[
primary_image
].freeze

class Profile < ApplicationRecord
   has_one_attached :primary_image, dependent: :purge


```
If primary_image is included in the show page attributes, I get the above error - undefined method `primary_image_admin_profile_path' for #<#<Class....

Am I forgetting something basic?

Thanks.

**Comment by Dreamersoul** [comment]
Can you show the options being sent to the primary image in the `ATTRIBUTE_TYPES` hash?

**Comment by Dreamersoul** [comment]
related #39

**Comment by wilpar** [comment]
Sorry for the delay getting back here.  As I understand the question, there are no options sent to the primary image.

I have additional images split into a separate model, which isn't as cluttered as the Profile model above. It has the same problem, so let me use that as an example instead.

The index action works fine.  It's the show action that crashes

image.rb:
```
class Image < ApplicationRecord
  belongs_to :profile

  has_one_attached :file
  delegate_missing_to :file

  validates :file, presence: true, blob: { content_type: :image }

	extend FriendlyId
	friendly_id :uuid, use: [:slugged, :finders]

  private

	  def uuid
	    slug || SecureRandom.uuid
	  end
end
```
image_dashboard.rb:
```

require "administrate/base_dashboard"

class ImageDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    profile: Field::BelongsTo,
    file: Field::ActiveStorage,
    id: Field::Number,
    slug: Field::String,
    approved: Field::Boolean,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze

SHOW_PAGE_ATTRIBUTES = %i[
  profile
  file
  id
  slug
  approved
  created_at
  updated_at
  ].freeze

```

**Comment by wilpar** [comment]
Confirmed from #39 adding

```
.with_options(destroy_url: nil,),
```
fixes the show action.

**Comment by phoet** [comment]
@Dreamersoul could you reopen this? the workaround helps, but this looks like it has been fixed and the other issue is something very different (at least from the description).

**Comment by Dreamersoul** [comment]
correct, i will be pushing an update that fixes both issues
