### ISSUE TITLE
File path is not shown when show_display_preview is set to false

### ISSUE THREAD

**Issue by leifg** [Dreamersoul/administrate-field-active_storage#40]
Related to #37 there is an issue with the latest version (0.3.2).

With the change of `url_only` to `show_display_preview` it seems as if there is absolutely now preview when you set `show_display_preview` to false.

This is how it looks like in 0.2.2:

<img width="1306" alt="Screenshot 2020-04-23 11 58 10" src="https://user-images.githubusercontent.com/110321/80138750-2145e100-855a-11ea-8aea-e25e60859a7a.png">

And with version 0.3.2 I just see a download button:

<img width="1307" alt="Screenshot 2020-04-23 11 58 58" src="https://user-images.githubusercontent.com/110321/80138767-2acf4900-855a-11ea-8c95-4ea2cb392523.png">

Is this intentional? Do I not have the opportunity to show the filename to distinguish different files?

**Comment by Dreamersoul** [comment]
I think this was intentional but I agree with you file names are important, I'll push an update that shows the filename
