### ISSUE TITLE
Question on Active Storage validation

### ISSUE THREAD

**Issue by loumarven** [Dreamersoul/administrate-field-active_storage#41]
Hi there,

Thanks for creating this gem.
Just wanted to ask how this gem handles Active Storage validations.
I was looking at the [field options](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/lib/administrate/field/active_storage.rb) but I'm not sure which one to set (or is there?) to create validations for my attachment(s).
I know there are some solutions available (client side, another [gem](https://github.com/igorkasyanchuk/active_storage_validations)), but I'm curious how this gem handles validations (if supported).

By the way, here are the versions that I use:

- Ruby 2.6.5
- Rails 5.2.4.2
- Administrate 0.13.0

Thank you!

**Comment by Dreamersoul** [comment]
Validations happen on the model level, not the administrate gem, I use the following gem for validation
https://github.com/aki77/activestorage-validator

**Comment by loumarven** [comment]
Thanks for the validator gem you mentioned!
