### ISSUE TITLE
Error on loading "image/webp"

### ISSUE THREAD

**Issue by bekicot** [Dreamersoul/administrate-field-active_storage#43]
It seems like imagemagic cannot create a variant for "image/webp"

Posible Solution:
Make sure that the image processor can create variation of specified content type.

https://github.com/Dreamersoul/administrate-field-active_storage/blob/9e2f2eb31b13d3891e4830139b32605855775df3/lib/administrate/field/active_storage.rb#L53

**Comment by sedubois** [comment]
I belive this is fixed in Rails 6.1.0.alpha by adding a config option:
https://github.com/rails/rails/pull/38988

**Comment by bekicot** [comment]
That's awesome. I didn't notice that, thank you.

I also just realize that I use old version of this gem.
It should be fixed by this https://github.com/Dreamersoul/administrate-field-active_storage/commit/349fe57bf6e52c8726abddd4606c9a920c0173c6#diff-db9256b46dc4bb1e197aabcc5bf747a6
