### ISSUE TITLE
Extend administrate generator

### ISSUE THREAD

**Issue by FWMatt** [Dreamersoul/administrate-field-active_storage#44]
Hi,

Great work with this plugin. 

Any thoughts on how to instruct the main administrate generate command to use the `Field::ActiveStorage` type?

i.e.
`rails generate administrate:install`

Currently results in 

<img width="291" alt="Screenshot 2020-05-29 at 11 47 28" src="https://user-images.githubusercontent.com/946513/83252025-73ee6a80-a1a2-11ea-8be2-6bd2e51c2214.png">

When it should be

<img width="281" alt="Screenshot 2020-05-29 at 11 47 41" src="https://user-images.githubusercontent.com/946513/83252042-79e44b80-a1a2-11ea-93f8-eca79dd31bd8.png">

**Comment by Dreamersoul** [comment]
To be honest I Don't know maybe if our gem gets merged into adminstrate then we maybe hook up to their generators

**Comment by sedubois** [comment]
@pablobm @nickcharlton would you have a suggestion?

If it's not possible ATM, how about defining an interface like `def self.accept?(attribute)` in  `Administrate::Field::Base`, having that method getting called for all the available field types until it finds a compatible one? Similar to how ActiveStorage looks for a Previewer suitable for a specific blob ([ref](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/previewer.rb#L12)). Just need to pay attention in which order the fields will be looked up.

**Comment by nickcharlton** [comment]
👋, I'm not aware of it being possible to hook into the generators, but this would be a good feature to add for every plugin.

**Comment by Dreamersoul** [comment]
closing this as this is not concerning the gem per say however people from [thoughtbot/administrate](https://github.com/thoughtbot/administrate) are welcome to include the gem into their framework
