### ISSUE TITLE
Variant combine_options deprecated, disappears in Rails 6.1

### ISSUE THREAD

**Issue by sedubois** [Dreamersoul/administrate-field-active_storage#47]
Administrate::Field::ActiveStorage passes a parameter called `combine_options` when making a variant:

https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/lib/administrate/field/active_storage.rb#L53

My understanding is that this is forwarded to the `ImageProcessingTransformer`? If that is the case, this is deprecated and will disappear in Rails 6.1:
https://github.com/rails/rails/blob/4304373788fda6fa0fb1d6bac4ef78fb1ecac3dd/activestorage/lib/active_storage/transformers/image_processing_transformer.rb#L25

**Comment by Dreamersoul** [comment]
Oh yeah that makes sense maybe we should issue a breaking change to the gem!
