### ISSUE TITLE
How do you customize the field?

### ISSUE THREAD

**Issue by AFlowOfCode** [Dreamersoul/administrate-field-active_storage#49]
I need to customize the field view & couldn't find an easy way to access it. Using Administrate's `rails g administrate:views:field <field>` command with ActiveStorage doesn't work. It would be nice and consistent if it did, but maybe it's not possible to edit that generator. I think it would actually be best if this gem just generated the views directly into views/fields/active_storage by default, since it's only one field and it's important to have them accessible. What do you suggest regarding access to the views for customization?

**Comment by sedubois** [comment]
You can normally copy the view you need in your own project:
https://github.com/Dreamersoul/administrate-field-active_storage/tree/master/app/views/fields/active_storage

**Comment by AFlowOfCode** [comment]
I didn't realize you could override it manually like that. A method aside from coming to copy a file from the repo when you realize you have to change something could be useful, just my 2 cents! Thank you!
