### ISSUE TITLE
Unable to add more attachments - existing attachments get overwritten by new upload

### ISSUE THREAD

**Issue by vitkoz** [Dreamersoul/administrate-field-active_storage#51]
I am unable to add another image to a record. Every next upload overrides existing files. I've followed the instructions for has_many_attached to a T. Any insight?

**Comment by Dreamersoul** [comment]
Hello, can you create an example project where I can test it and see where the issue is?

**Comment by iamnader** [comment]
This started happening for me as well. Didn't use to happen

**Comment by Dreamersoul** [comment]
@iamnader can you create an example project with the issue and link it so I can take a look at it and determine the isssue?

**Comment by iamnader** [comment]
I was able to solve it by setting this config: `Rails.application.config.active_storage.replace_on_assign_to_many = false`

It's a new default in Rails 6

**Comment by Dreamersoul** [comment]
Ohh thanks! We can add that to the readme file, if you can do it I can merge it today. Or I can do it tomorrow whenever I get the chance.

**Comment by iamnader** [comment]
I created a PR.  Thanks
