### ISSUE TITLE
figure out a way to delete file when has_many_attached

### ISSUE THREAD

**Issue by Dreamersoul** [Dreamersoul/administrate-field-active_storage#6]

**Comment by Dreamersoul** [comment]
Consider suggesting adding the attachment table as a relation

**Comment by Dreamersoul** [comment]
I meant destroying one file from a HasMany relationship

**Comment by mariozig** [comment]
Got it.  I can try to help you with this but unfortunately yesterday was my first time working with both Active Storage and Administrate; i'll try my best!

Last night/today I got started: https://github.com/mariozig/administrate-field-active_storage

So far I've updated the views to support a `removable` flag when rendering an attached item or collection of attached items.  It will only show this link when rendering the `form` partial -- `show` pages will not.

Currently the `remove` links do nothing and I'm trying to figure out where to take it from there.  If you have examples of how to add controllers/routes to an administrate plugin that would be awesome.  I've looked around github and couldn't find anything yet.

**Comment by Dreamersoul** [comment]
Really awesome progress! Thank you for your time honestly! I don't know how to add routes but administrate has controllers but I don't think we can add something to the field. Maybe we need to look up the remove URL from rails itself. Or let the user add a route with a controller method to activate the remove link

**Comment by mariozig** [comment]
Sorry for the delay -- my wife and i just had a kid so i've only been working on it like 1% :) 

Based on your input I hacked something together that works: https://github.com/mariozig/administrate-field-active_storage/commit/43a67e5cc303438acd10c3d558253a1a53d111fc 

I've integrated it into an app i'm working on and it doing the job! I will clean up the code and submit PR soon. 

BTW thanks so much for your work in creating this administrate extension!

**Comment by Dreamersoul** [comment]
Thank you for this amazing contribution! Congratulations on the kid :smile: 
I will look into it once I can.take your time with the PR!

**Comment by Dreamersoul** [comment]
just looked into the changes you made and i approve them 👍 awesome progress. will merge whenever you issue a PR. please don't forget documentation and adding your name to the contributors file. 🚀

**Comment by Dreamersoul** [comment]
any updates? @mariozig 😄

**Comment by leifg** [comment]
That would be an awesome feature to have

**Comment by Dreamersoul** [comment]
I think I'm gonna implement it soon, I want to get informed with the activestorage API because I don't want the developer to add a route to their websites

**Comment by leifg** [comment]
I tested the code. Works like a charm, thank you for this!!!

The only optimization I would make is passing the record type to the endpoint:

```ruby
      def destroy_path(field, attachment)
        destroy_path_helper = options.fetch(:destroy_path)
        record_id = field.data.record.id
        record_type = field.data.record.class.name
        attachment_id = attachment.id

        Rails.application.routes.url_helpers.send(destroy_path_helper, record_type, record_id, attachment_id)
      end
```

That would make it very easy to provide a generic endpoint for deletion of attachments.

**Comment by Dreamersoul** [comment]
sorry for the late reply! i didn't have time to check into this. if you have a solution can you please create a PR? thank you!

**Comment by leifg** [comment]
Well the solution is already there.

It is literally the code in @mariozig master branch. I didn't add any additional code.

My suggestion is just an improvement to that solution.

**Comment by Dreamersoul** [comment]
Thank you for the suggestion! I currently have no time to implement what @mariozig did! If you can push it as a PR I would appreciate it! If not I'll try to find some time this weekend to implement this

**Comment by leifg** [comment]
Pull request opened.

Note: this is the code from @mariozig's master branch
