### ISSUE TITLE
Removable is not passed into local assigns and therefore cannot be enabled

### ISSUE THREAD

**Issue by sherwyngoh** [Dreamersoul/administrate-field-active_storage#64]
From https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_form.html.erb

`<%= render partial: 'fields/active_storage/items', locals: { field: field } %>`

For the above, if removable is not passed in, what is the intended way to provide the local_assigns?

https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_items.html.erb

`removable = local_assigns.fetch(:removable, false)`

**Comment by Dreamersoul** [comment]
If I remember correctly removable gets assigned as true if you specify a destroy url

**Comment by sherwyngoh** [comment]
@Dreamersoul  holy wow thats fast, thanks! - `<% if field.destroy_url.present? %>` Yes I have found this - let me have a quick look and close this issue afterwards.

**Comment by sherwyngoh** [comment]
@Dreamersoul  I've tried 2 specify it two ways, currently unsuccessful.

```
  namespace :admin do
    resources :users
    resources :products do
      delete :images, on: :member, action: :destroy_image # first way
    end

    delete "products/:id/images/:attachment_id", action: :destroy_image, controller: "products", as: :destroy_product_image #second way
```

For reference:
`has_many_attached :images ` is under Product.rb and the upload works fine.

Thank you for this so far 👍 . Any tips on inspecting this so I can fix this myself without troubling you further?

**Comment by Dreamersoul** [comment]
I'm glad my timing helps you get the work done faster haha I try to be a good maintainer


Can I have a look at how you specify the destroy url on the dashboard file? In the readme file we have a working example 

also I might share how I usually do it when I get home

**Comment by sherwyngoh** [comment]
Found it! Thank you @Dreamersoul Let me know if I can help with anything.
