### ISSUE TITLE
Way to  search on the file name 

### ISSUE THREAD

**Issue by arpu** [Dreamersoul/administrate-field-active_storage#71]
Hey,

is there a way to search for the file name?

**Comment by Dreamersoul** [comment]
Not yet, I'm happy to merge a PR though!

**Comment by Dreamersoul** [comment]
closed for inactivity

**Comment by arpu** [comment]
can you give us some hints how to implement this?

**Comment by Dreamersoul** [comment]
Honestly I don't know how, however there is a search function in administe where you might be able to override to look up file names
