### ISSUE TITLE
Getting error undefined method `attached?' for #<ActiveStorage::Attachment..>

### ISSUE THREAD

**Issue by sjdweb** [Dreamersoul/administrate-field-active_storage#72]
Couldn't find anything on Google. Would you have any pointers? Thanks

```
Showing administrate-field-active_storage-0.3.7/app/views/fields/active_storage/_index.html.erb where line #18 raised:

undefined method `attached?' for #<ActiveStorage::Attachment id: 1, name: "logo", record_type: "Location", record_id: 1, blob_id: 5, created_at: "2021-07-01 02:51:58.469099000 +0000">
```

Also traces back in Honeybadger to here

```
active_storage.rb  69  attached?(...)
[GEM_ROOT]/gems/administrate-field-active_storage-0.3.7/lib/administrate/field/active_storage.rb:69:in `attached?'
```

**Comment by Dreamersoul** [comment]
Hm that's weird it should work,
Can I get a snippet on how you added the fields to the dashboard file?

**Comment by sjdweb** [comment]
@Dreamersoul hey -- so figured it out! So when you generate a dashboard via the cli, it specified the field name as:

```
    logo_attachment: Field::ActiveStorage,
```

So that caused the confusion. The field on the model is just `logo`, not sure why it has `_attachment` at the end.

Changing to this
```
    logo: Field::ActiveStorage,

```

Fixed the problem.


Hopefully this helps in the future for whoever finds this error on Google!

Cheers

**Comment by sebastienbourda** [comment]
> @Dreamersoul hey -- so figured it out! So when you generate a dashboard via the cli, it specified the field name as:
> 
> ```
>     logo_attachment: Field::ActiveStorage,
> ```
> 
> So that caused the confusion. The field on the model is just `logo`, not sure why it has `_attachment` at the end.
> 
> Changing to this
> 
> ```
>     logo: Field::ActiveStorage,
> ```
> 
> Fixed the problem.
> 
> Hopefully this helps in the future for whoever finds this error on Google!
> 
> Cheers


Thanks. 

In my case, i needed to remove:
from routes
```
resources :attachments
resources :blobs
```
from ModelDashboard all
```
 cover_image_blob
```

Then modified:

```
    cover_image_attachment
```
To
```
    cover_image
```
