### ISSUE TITLE
Inline style doesn't work with Content Security Policy

### ISSUE THREAD

**Issue by michaelbaisch** [Dreamersoul/administrate-field-active_storage#79]
Hello,

after enabling CSP I get a quite a lot of errors in the browser console in administrate views where this gem is used.

```
Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.
```

In the errors is [this](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_index.html.erb#L19), [this](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_preview.html.erb#L1), [this](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_preview.html.erb#L14) and [this](https://github.com/Dreamersoul/administrate-field-active_storage/blob/master/app/views/fields/active_storage/_preview.html.erb#L16) referenced: 

```erb
<!-- _index.html.erb -->
<style> <%# figure out a way to remove this %>
  td img {
    max-height: unset !important;
  }
</style>



<!-- _preview.html.erb -->
<div style="width: <%=size[0]%>px; height: auto; overflow: hidden;">


<% if attachment.previewable? %>
<%= video_tag(field.url(attachment),
        poster: field.preview(attachment, resize_to_limit: size),
        controls: true,
        autobuffer: true,
        style: "object-fit: contain; width: 100%; height: 100%;") %>
<% else %>
    <%= video_tag(field.url(attachment), controls: true, autobuffer: true, style: "object-fit: contain; width: 100%; height: 100%;") %>
<% end %>
```

Of course it would be best to put those in a separate stylesheet, but I realize that it's not that simple. Maybe someone comes up with a clever solution. In the meantime we could add a nonce to the style tag (and converting the problems in the second file, maybe with some kind of #id, also into a tag).

```html
<style type="text/css" nonce="<%= content_security_policy_nonce %>">
```

This also works when CSP is disabled.

Greetings,
Michael

**Comment by Dreamersoul** [comment]
This is a great write up of the issue, however I am not familiar with CSP and don't think I can fix it on my own! I am open for PR if you think you have a suitable solution that would benefit the library!
Thanks for the feedback
