### ISSUE TITLE
Default variant processor changed to vips in Rails 7

### ISSUE THREAD

**Issue by Alagaesia93** [Dreamersoul/administrate-field-active_storage#88]
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-storage-default-variant-processor-changed-to-vips

In order to use this gem, add in

config/application.rb
`config.active_storage.variant_processor = :mini_magick`

**Comment by Dreamersoul** [comment]
From what I remember if you have vips installed on your server you don't need this.
