### ISSUE TITLE
Option to use new Rails 7 named variants

### ISSUE THREAD

**Issue by michaelbaisch** [Dreamersoul/administrate-field-active_storage#90]
Hello,

I think it would be great if we could select from a predefined named variant. See end of:
https://edgeguides.rubyonrails.org/active_storage_overview.html#has-one-attached
This way we could define more complicated variants, which might already be used in the application and this way prevent creating a new variant version only for administrate.
I'm suggesting something like:

```ruby
avatar: Field::ActiveStorage.with_options(index_preview_variant: :thumb, show_preview_variant: :medium),
```

(PR work in progress)

Greetings

**Comment by Dreamersoul** [comment]
That would be great! For the PR don't forget to change the rails gem version to be 7 so that the update doesn't mess up peoples rails 6 configs
😄
