### ISSUE TITLE
Preview image not working — ArgumentError - Invalid variant format (:png)

### ISSUE THREAD

**Issue by gabrielguerin** [Dreamersoul/administrate-field-active_storage#99]
**Using Rails 7 and Ruby 2.7.5**

I am getting the following error `ArgumentError - Invalid variant format (:png)` when I am trying to display an image. I do not understand where the problem comes from. I have all [default views](https://github.com/Dreamersoul/administrate-field-active_storage/tree/master/app/views/fields/active_storage) and followed every step until [`has_one_attached`](https://github.com/Dreamersoul/administrate-field-active_storage/tree/master/app/views/fields/active_storage).

Here is the full trace:
```
Processing by ActiveStorage::Representations::RedirectController#show as PNG
  Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzhCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--82ebb89dc6b6d08d36521b264bf0152de4a45961", "variation_key"=>"[FILTERED]", "filename"=>"clinique_anne_artois_logo"}
  ActiveStorage::Blob Load (0.6ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 399], ["LIMIT", 1]]
  ActiveStorage::VariantRecord Load (1.7ms)  SELECT "active_storage_variant_records".* FROM "active_storage_variant_records" WHERE "active_storage_variant_records"."blob_id" = $1 AND "active_storage_variant_records"."variation_digest" = $2 LIMIT $3  [["blob_id", 399], ["variation_digest", "xlCz/aQast+KxvrbGvlyc7DaGjg="], ["LIMIT", 1]]
  Disk Storage (4.4ms) Downloaded file from key: iifumv2hhaf31nkhow1ostu2ez47
Completed 500 Internal Server Error in 71ms (ActiveRecord: 12.8ms | Allocations: 8808)

ArgumentError - Invalid variant format (:png):`
```

In my model's dashboard:
```
class PartnerDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    logo: Field::ActiveStorage.with_options(show_preview_variant: :thumb),
  }.freeze
  
  SHOW_PAGE_ATTRIBUTES = %i[
    logo
  ].freeze

  FORM_ATTRIBUTES = %i[
    logo
  ].freeze
  
  # [...]
end
```
  
In my model:

```
class Partner < ApplicationRecord
  has_one_attached :logo do |attachable|
    attachable.variant :thumb, resize_to_limit: [150, 150]
  end

  # [...]
end
```

**Comment by Dreamersoul** [comment]
After digging for a bit, turns out the issue is that your imagemagik doesn't have png support or something.

Here is the error that caused it [format error](https://apidock.com/rails/v6.1.3.1/ActiveStorage/Variation/format)

**Comment by gabrielguerin** [comment]
I've tried again and it still doesn't work (with a **jpg** image). It is weird because in the `_preview.html.erb` file, if I only insert the following code : `<%= image_tag(field.url(attachment)) %>`, then the app displays the image properly.

**Comment by Dreamersoul** [comment]
Hey are you still facing this issue?
